# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: Dockerfile

tasks:
  - init: node --version

  - command: node app.js

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
